### ISSUE TITLE
Type 30 background color

### ISSUE THREAD

**Issue by larsbrinkhoff** [hrvach/fpg1#2]
Hello,

What is your view on the background color of the Type 340 CRT?

Here is a photo of a Type 340, which I believe has the same CRT.
![20190325_143446](https://user-images.githubusercontent.com/775050/63494879-fda83380-c4be-11e9-888b-29f9b7eb053b.jpg)

As you can see, it's not actually black, but greenish gray.

**Comment by hrvach** [comment]
As far as I can tell, at least one version of these displays used the same tube, Raytheon 16ADP7A. It has the dual P7 phosphor coating which is known for its bright blue glow shortly after pixel is activated and this turns into a yellow-green afterglow, taking quite a long time to disappear. It was designed for radar screens in WW2 and found its use in these displays because the number of pixels per second you can activate is quite limited with the Type 30. To overcome this, you relied on the long afterglow so you didn't have to refresh pixels as fast as you would using other types of displays.

As far as the background color goes, it really depends on the background lighting of the room. Most phosphor coatings are not black per se and appear to be, as you said, greenish gray. It's a similar things with old TVs which I remember being quite obvious when sun struck part of the screen.

If you dim the lights, as you probably would when watching telly - it's quite black :)

**Comment by larsbrinkhoff** [comment]
Thanks!
